Quote.destroy_all
Quote.create content: 'Only the hand that erases can write the true thing.'
Quote.create content: 'It is the power of the mind to be unconquerable.'
Quote.create content: 'It is easy to believe we are each waves and forget we are also the ocean.'
Quote.create content: 'What was never lost can never be found.'
Quote.create content: 'We carry inside us the wonders we seek outside us.'
Quote.create content: 'The obstacle is the path.'
Quote.create content: 'If you are unable to find the truth right where you are, where else do you expect to find it?'
Quote.create content: 'Roaring dreams take place in a perfectly silent mind.'
Quote.create content: 'Smiling is one of the highest forms of meditation.'
Quote.create content: 'The mind can go in a thousand directions, but on this beautiful path, I walk in peace.'
Quote.create content: 'Smiling is one of the highest forms of meditation.'
Quote.create content: 'Meditation is the ultimate mobile device; you can use it anywhere, anytime, unobtrusively.'
Quote.create content: 'Three things cannot be long hidden: the sun, the moon, and the truth.'
